version: '3.8'

services:
  postgres:
    image: postgres:12
    environment:
      POSTGRES_USER: redash
      POSTGRES_PASSWORD: redash
      POSTGRES_DB: redash

  redis:
    image: redis:6

  redash:
    image: redash/redash:latest
    depends_on:
      - postgres
      - redis
    environment:
      REDASH_DATABASE_URL: "postgresql://redash:redash@postgres/redash"
      REDASH_REDIS_URL: "redis://redis:6379/0"
    ports:
      - "5000:5000"
